In [1]:
import numpy as np
import pandas as pd
from mlal1 import *
import math

In [2]:
pdf=pd.read_csv('classification_train.csv')
arr=pdf.to_numpy()
X_train=arr[0:10000,2:786]
y_train=arr[0:10000,1]
x=arr[0:10000,1:786]
print(x[0:10000,1:785])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [3]:
pdf2=pd.read_csv('classification_test.csv')
arr2=pdf2.to_numpy()
X_test=arr2[0:10000,1:785]
id_test=arr2[0:10000,0]

In [4]:
print(X_train.shape)
print(X_test.shape)
print(id_test.shape)


(10000, 784)
(10000, 784)
(10000,)


In [5]:
def cal_eucleadian_distance(x1,x2):
    return np.sqrt(np.sum(np.square(x1-x2),axis=1))

In [9]:
def cal_pred(x1,x2):
    k=100
    distance=cal_eucleadian_distance(x1[:,1:785],x2)
    indices=np.argsort(distance)
    predicted_value=np.mean(x1[indices[0:k],0])
    return predicted_value

In [10]:
predictions=[]
m,n=X_test.shape
for i in range(m):
    predicted_value=cal_pred(x,X_test[i,:])
    
    pred=math.modf(predicted_value)
    if(pred[0]>=0.5):
        predictions.append(pred[1]+1)
    else:
        predictions.append(pred[1])
print(predictions)
pdf2['label1']=predictions


[1.0, 1.0, 4.0, 3.0, 3.0, 4.0, 8.0, 5.0, 5.0, 1.0, 3.0, 4.0, 4.0, 4.0, 8.0, 5.0, 5.0, 3.0, 5.0, 4.0, 4.0, 4.0, 3.0, 1.0, 6.0, 8.0, 8.0, 5.0, 4.0, 1.0, 8.0, 7.0, 8.0, 8.0, 1.0, 1.0, 9.0, 6.0, 3.0, 4.0, 3.0, 3.0, 4.0, 4.0, 4.0, 0.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 9.0, 3.0, 0.0, 9.0, 9.0, 4.0, 3.0, 2.0, 4.0, 8.0, 5.0, 5.0, 2.0, 1.0, 1.0, 9.0, 7.0, 3.0, 7.0, 2.0, 4.0, 3.0, 5.0, 7.0, 1.0, 5.0, 1.0, 3.0, 9.0, 4.0, 1.0, 4.0, 4.0, 8.0, 9.0, 4.0, 1.0, 5.0, 3.0, 3.0, 4.0, 4.0, 4.0, 3.0, 4.0, 7.0, 7.0, 3.0, 9.0, 3.0, 9.0, 5.0, 5.0, 3.0, 3.0, 4.0, 3.0, 7.0, 6.0, 6.0, 4.0, 4.0, 7.0, 6.0, 2.0, 4.0, 7.0, 2.0, 1.0, 6.0, 4.0, 4.0, 7.0, 2.0, 7.0, 7.0, 1.0, 3.0, 1.0, 7.0, 9.0, 4.0, 9.0, 5.0, 4.0, 4.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 3.0, 5.0, 3.0, 1.0, 1.0, 3.0, 4.0, 3.0, 3.0, 1.0, 9.0, 3.0, 3.0, 3.0, 9.0, 6.0, 5.0, 7.0, 7.0, 3.0, 4.0, 4.0, 1.0, 4.0, 7.0, 4.0, 4.0, 8.0, 9.0, 1.0, 4.0, 4.0, 4.0, 7.0, 7.0, 9.0, 7.0, 1.0, 3.0, 9.0, 1.0, 7.0, 6.0, 5.0, 0.0, 7.0, 4.0, 8.0, 1.0, 5.0, 3.0, 0.0, 4.0, 5.0, 4.0, 9.0,

In [11]:
X1=pdf2[['ids','label1']]
print(X1.head(5))

     ids  label1
0  25672     1.0
1  59964     1.0
2  66230     4.0
3  50801     3.0
4  83307     3.0
